// The prop kit — PURE DATA. No THREE.
//
// Team Bondage had six props: snowman, fence post, hay bale, barrel, crate,
// tractor. Six objects across 4096 tiles is a field with some things on it,
// not a working farm in winter, and the three new maps had nothing of their
// own at all. Bryan: "add more props based on the idea of the game being a
// barn, farm, game set in winter with shooter characteristics".
//
// These are built in code rather than as Blender GLBs. The existing six are
// GLBs generated by the art styler and they stay that way; a GLB is the right
// home for a prop that wants a baked texture atlas. But a GLB is also 150
// lines of Python, a Blender run and a binary in the repo per object, and the
// thing this pass needed was TWENTY-SEVEN objects across four maps. Voxel
// boxes in a data file get there, follow the same spec/test pattern as
// viewmodelSpec / hazardSpec / skyBrawlSpec, and cost nothing to load.
//
// Model space: +X right, +Y up, +Z forward. Origin sits on the ground, so
// y=0 is the tile surface the prop stands on.
//
// The bar each prop has to clear (docs/GRAPHICS_QUALITY_LOOP.md, "Minecraft-
// tier"): a recognisable SILHOUETTE and at least TWO material tones. A prop
// that is one flat colour is a coloured box, and the map already has crates.
//
// # PLACEHOLDER ART — procedural, due a hand-drawn pass per DESIGN_PRINCIPLES.

// -- Palette ----------------------------------------------------------------
// Shared with the rest of the game so a new prop can never introduce a
// twenty-eighth brown.
const WOOD       = 0x8a5a2b;
const WOOD_DARK  = 0x5e3c1c;
const WOOD_PALE  = 0xb08048;
const METAL      = 0x8d949c;
const METAL_DARK = 0x555b63;
const RUST       = 0x9c5a32;
const SNOW       = 0xeef5fb;
const ICE        = 0xb8e0ef;
const HAY        = 0xf5d53a;
const CLOTH_RED  = 0xb73a2a;
const CLOTH_BLUE = 0x336bbf;
const BLACK      = 0x1e1c1a;
const PINE_DARK  = 0x1d3d2d;
const PINE_MID   = 0x2c563e;
const LAMP_GLOW  = 0xffe9a8;
const STONE      = 0x6d7076;
const CANVAS     = 0xe8e2d4;
const FLESH      = 0xc65a4a;

const P = (x, y, z, w, h, d, hex, extra) => ({ p: [x, y, z, w, h, d], hex, ...extra });

// ---------------------------------------------------------------------------
// The kit
// ---------------------------------------------------------------------------
export const PROPS = Object.freeze({

  // -- Farm -----------------------------------------------------------------

  // A water trough, frozen solid. The ice sits proud of the rim, which is what
  // says "frozen" rather than "empty".
  trough: [
    P(0, 0.10, 0, 1.70, 0.20, 0.70, WOOD_DARK),
    P(0, 0.42, 0.32, 1.70, 0.45, 0.10, WOOD),
    P(0, 0.42, -0.32, 1.70, 0.45, 0.10, WOOD),
    P(0.83, 0.42, 0, 0.10, 0.45, 0.70, WOOD),
    P(-0.83, 0.42, 0, 0.10, 0.45, 0.70, WOOD),
    P(0, 0.56, 0, 1.55, 0.14, 0.58, ICE),
    P(0, 0.64, 0.14, 0.70, 0.05, 0.20, SNOW),
  ],

  // Milk churn: the classic tapered can with a domed lid and two lug handles.
  'milk-churn': [
    P(0, 0.06, 0, 0.52, 0.12, 0.52, METAL_DARK),
    P(0, 0.42, 0, 0.58, 0.62, 0.58, METAL),
    P(0, 0.80, 0, 0.44, 0.18, 0.44, METAL),
    P(0, 0.94, 0, 0.34, 0.12, 0.34, METAL_DARK),
    P(0, 1.02, 0, 0.14, 0.08, 0.14, METAL),
    P(0.31, 0.72, 0, 0.06, 0.16, 0.16, METAL_DARK),
    P(-0.31, 0.72, 0, 0.06, 0.16, 0.16, METAL_DARK),
    P(0, 1.06, 0, 0.36, 0.06, 0.36, SNOW),
  ],

  // Split logs stacked in a crib, snow along the top.
  'log-pile': [
    P(0, 0.18, 0.30, 1.60, 0.36, 0.36, WOOD_DARK),
    P(0, 0.18, -0.10, 1.60, 0.36, 0.36, WOOD),
    P(0, 0.54, 0.10, 1.60, 0.36, 0.36, WOOD_DARK),
    P(0, 0.54, -0.28, 1.40, 0.36, 0.36, WOOD_PALE),
    P(0, 0.86, -0.06, 1.20, 0.30, 0.32, WOOD),
    P(0, 1.03, -0.06, 1.24, 0.10, 0.36, SNOW),
    P(0.82, 0.55, 0.10, 0.06, 1.10, 0.08, WOOD_DARK),   // crib post
    P(-0.82, 0.55, 0.10, 0.06, 1.10, 0.08, WOOD_DARK),
  ],

  // A chopping block with the axe still buried in it.
  'chopping-block': [
    P(0, 0.30, 0, 0.70, 0.60, 0.70, WOOD),
    P(0, 0.62, 0, 0.72, 0.06, 0.72, WOOD_PALE),
    P(0.10, 0.98, 0, 0.06, 0.70, 0.06, WOOD_DARK, { tiltZ: 0.30 }),  // haft
    P(0.28, 1.30, 0, 0.10, 0.26, 0.22, METAL, { tiltZ: 0.30 }),      // head
    P(-0.45, 0.08, 0.30, 0.34, 0.16, 0.30, WOOD_PALE),               // split billet
  ],

  wheelbarrow: [
    P(0, 0.42, 0, 0.80, 0.40, 0.60, METAL),
    P(0, 0.60, 0, 0.68, 0.12, 0.50, RUST),
    P(-0.62, 0.34, 0.20, 0.90, 0.06, 0.06, WOOD),   // handles
    P(-0.62, 0.34, -0.20, 0.90, 0.06, 0.06, WOOD),
    P(0.46, 0.22, 0, 0.10, 0.44, 0.44, BLACK),      // wheel
    P(0.30, 0.10, 0.22, 0.06, 0.22, 0.06, METAL_DARK),
    P(0.30, 0.10, -0.22, 0.06, 0.22, 0.06, METAL_DARK),
    P(0, 0.70, 0, 0.60, 0.10, 0.44, SNOW),
  ],

  // A slumped hessian sack of feed with grain spilling out of the neck.
  'feed-sack': [
    P(0, 0.26, 0, 0.62, 0.52, 0.48, CANVAS),
    P(0, 0.56, 0, 0.44, 0.16, 0.36, CANVAS),
    P(0, 0.68, 0, 0.20, 0.14, 0.18, WOOD_PALE),
    P(0.20, 0.66, 0.10, 0.16, 0.06, 0.14, HAY),
    P(0.34, 0.03, 0.14, 0.36, 0.06, 0.26, HAY),     // spill
    P(0, 0.30, 0.25, 0.30, 0.10, 0.02, WOOD_DARK),  // stencil band
  ],

  // Snow-caked scarecrow: crossed pole, straw arms, sack head, battered hat.
  scarecrow: [
    P(0, 0.85, 0, 0.10, 1.70, 0.10, WOOD_DARK),
    P(0, 1.30, 0, 1.30, 0.08, 0.08, WOOD_DARK),
    P(0, 1.16, 0, 0.60, 0.60, 0.34, CLOTH_RED),
    P(0.62, 1.24, 0, 0.24, 0.14, 0.14, HAY),        // straw cuffs
    P(-0.62, 1.24, 0, 0.24, 0.14, 0.14, HAY),
    P(0, 1.62, 0, 0.38, 0.36, 0.34, CANVAS),        // sack head
    P(0.09, 1.66, 0.18, 0.08, 0.08, 0.02, BLACK),   // stitched eyes
    P(-0.09, 1.66, 0.18, 0.08, 0.08, 0.02, BLACK),
    P(0, 1.84, 0, 0.44, 0.10, 0.44, WOOD_DARK),     // hat brim
    P(0, 1.94, 0, 0.28, 0.16, 0.28, WOOD_DARK),
    P(0, 2.03, 0, 0.30, 0.05, 0.30, SNOW),
    P(0, 0.10, 0, 0.36, 0.14, 0.36, SNOW),          // drift at the foot
  ],

  // Weather vane on a post — a rooster on a cross of cardinals.
  'weather-vane': [
    P(0, 1.05, 0, 0.14, 2.10, 0.14, WOOD_DARK),
    P(0, 2.14, 0, 0.90, 0.05, 0.05, METAL_DARK),
    P(0, 2.14, 0, 0.05, 0.05, 0.90, METAL_DARK),
    P(0, 2.34, 0, 0.06, 0.36, 0.06, METAL_DARK),
    P(0.02, 2.50, 0.16, 0.05, 0.26, 0.44, METAL),   // rooster body
    P(0.02, 2.66, 0.36, 0.05, 0.16, 0.14, METAL),   // head
    P(0.02, 2.60, -0.10, 0.05, 0.30, 0.22, RUST),   // tail
    P(0, 2.10, 0, 0.20, 0.06, 0.20, SNOW),
  ],

  // Oil drum brazier: a rusted drum with a fire going in the top.
  'oil-drum': [
    P(0, 0.44, 0, 0.62, 0.88, 0.62, RUST),
    P(0, 0.20, 0, 0.66, 0.08, 0.66, METAL_DARK),
    P(0, 0.68, 0, 0.66, 0.08, 0.66, METAL_DARK),
    P(0, 0.90, 0, 0.50, 0.06, 0.50, BLACK),
    P(0, 1.00, 0, 0.28, 0.20, 0.24, 0xf07a2a, { glow: 0.7 }),
    P(0.10, 1.14, 0.04, 0.14, 0.16, 0.12, 0xffc24a, { glow: 1.0 }),
    P(-0.08, 1.10, -0.04, 0.10, 0.12, 0.10, 0xffe9a8, { glow: 1.0 }),
  ],

  kennel: [
    P(0, 0.32, 0, 1.00, 0.64, 0.90, WOOD),
    P(0, 0.06, 0, 1.06, 0.12, 0.96, WOOD_DARK),
    P(0, 0.72, 0, 0.72, 0.24, 0.94, WOOD_DARK),     // pitched-ish roof
    P(0, 0.86, 0, 0.36, 0.18, 0.94, WOOD_DARK),
    P(0, 0.97, 0, 0.42, 0.06, 0.98, SNOW),
    P(0, 0.30, 0.46, 0.38, 0.52, 0.04, BLACK),      // doorway
    P(0, 0.66, 0.47, 0.30, 0.10, 0.02, WOOD_PALE),  // name board
  ],

  // -- Shooter furniture (every map) ----------------------------------------

  // A sandbag revetment: two courses, running bond, snow on the top row.
  'sandbag-wall': [
    P(-0.55, 0.14, 0, 0.52, 0.28, 0.42, CANVAS),
    P(0.00, 0.14, 0, 0.52, 0.28, 0.42, 0xd8d0bc),
    P(0.55, 0.14, 0, 0.52, 0.28, 0.42, CANVAS),
    P(-0.28, 0.42, 0, 0.52, 0.28, 0.42, 0xd8d0bc),
    P(0.28, 0.42, 0, 0.52, 0.28, 0.42, CANVAS),
    P(0.00, 0.70, 0, 0.52, 0.28, 0.42, 0xd8d0bc),
    P(0.00, 0.86, 0, 0.56, 0.06, 0.46, SNOW),
  ],

  'ammo-crate': [
    P(0, 0.24, 0, 0.90, 0.48, 0.56, 0x4a5240),
    P(0, 0.50, 0, 0.94, 0.10, 0.60, 0x3a4232),
    P(0, 0.24, 0.29, 0.60, 0.14, 0.02, HAY),        // stencil
    P(0.40, 0.24, 0, 0.06, 0.30, 0.40, METAL_DARK), // latches
    P(-0.40, 0.24, 0, 0.06, 0.30, 0.40, METAL_DARK),
    P(0, 0.57, 0, 0.80, 0.05, 0.50, SNOW),
  ],

  // -- Mountain --------------------------------------------------------------

  // A snow-laden conifer. Three tapering skirts — a cone would read as a
  // traffic cone at 10 m; the stepped skirts are what make it a fir.
  pine: [
    P(0, 0.35, 0, 0.24, 0.70, 0.24, WOOD_DARK),
    P(0, 0.95, 0, 1.70, 0.55, 1.70, PINE_DARK),
    P(0, 1.20, 0, 1.80, 0.10, 1.80, SNOW),
    P(0, 1.60, 0, 1.25, 0.50, 1.25, PINE_MID),
    P(0, 1.82, 0, 1.32, 0.09, 1.32, SNOW),
    P(0, 2.20, 0, 0.80, 0.45, 0.80, PINE_DARK),
    P(0, 2.40, 0, 0.86, 0.08, 0.86, SNOW),
    P(0, 2.72, 0, 0.36, 0.42, 0.36, PINE_MID),
    P(0, 2.95, 0, 0.20, 0.16, 0.20, SNOW),
  ],

  // A summit cairn: stacked flat stones, tapering, with a marker on top.
  cairn: [
    P(0, 0.11, 0, 0.86, 0.22, 0.80, STONE),
    P(0.04, 0.31, 0, 0.74, 0.20, 0.70, 0x7d8087),
    P(-0.03, 0.49, 0.03, 0.62, 0.18, 0.60, STONE),
    P(0.02, 0.65, -0.02, 0.48, 0.16, 0.46, 0x5c5f65),
    P(0, 0.79, 0, 0.34, 0.14, 0.32, STONE),
    P(0, 0.92, 0, 0.20, 0.14, 0.18, SNOW),
    P(0, 1.12, 0.02, 0.05, 0.30, 0.05, CLOTH_RED),  // marker wand
  ],

  'ski-pair': [
    P(-0.10, 0.60, 0, 0.10, 1.30, 0.30, CLOTH_RED, { tiltZ: 0.12 }),
    P(0.12, 0.62, 0.04, 0.10, 1.30, 0.30, CLOTH_BLUE, { tiltZ: -0.10 }),
    P(-0.10, 1.28, 0, 0.12, 0.14, 0.22, BLACK),
    P(0.12, 1.30, 0.04, 0.12, 0.14, 0.22, BLACK),
    P(0.34, 0.55, -0.10, 0.04, 1.20, 0.04, METAL, { tiltZ: -0.18 }),   // poles
    P(0.44, 0.55, -0.14, 0.04, 1.20, 0.04, METAL, { tiltZ: -0.22 }),
    P(0, 0.06, 0, 0.60, 0.12, 0.44, SNOW),
  ],

  'ice-axe-rack': [
    P(-0.55, 0.50, 0, 0.10, 1.00, 0.10, WOOD_DARK),
    P(0.55, 0.50, 0, 0.10, 1.00, 0.10, WOOD_DARK),
    P(0, 0.92, 0, 1.20, 0.10, 0.10, WOOD),
    P(-0.30, 0.62, 0.02, 0.05, 0.62, 0.05, WOOD_PALE),
    P(-0.30, 0.94, 0.02, 0.34, 0.07, 0.10, METAL),
    P(0.10, 0.62, 0.02, 0.05, 0.62, 0.05, WOOD_PALE),
    P(0.10, 0.94, 0.02, 0.34, 0.07, 0.10, METAL_DARK),
    P(0, 0.04, 0, 1.30, 0.08, 0.30, SNOW),
  ],

  sled: [
    P(0, 0.22, 0, 0.62, 0.08, 1.20, WOOD_PALE),
    P(0.26, 0.10, 0, 0.08, 0.20, 1.30, WOOD_DARK),  // runners
    P(-0.26, 0.10, 0, 0.08, 0.20, 1.30, WOOD_DARK),
    P(0, 0.34, -0.46, 0.56, 0.20, 0.08, WOOD),      // backrest
    P(0, 0.29, 0.30, 0.50, 0.06, 0.40, CLOTH_RED),  // blanket
    P(0, 0.24, 0.62, 0.20, 0.04, 0.30, WOOD_DARK),  // tow rope anchor
  ],

  // -- Central Park ----------------------------------------------------------

  // A cast-iron park lamp. The tallest thing on the rink map and its main
  // vertical, so it is deliberately over-scale.
  'lamp-post': [
    P(0, 0.12, 0, 0.44, 0.24, 0.44, BLACK),
    P(0, 0.30, 0, 0.30, 0.20, 0.30, METAL_DARK),
    P(0, 1.60, 0, 0.16, 2.40, 0.16, BLACK),
    P(0, 2.86, 0, 0.26, 0.16, 0.26, METAL_DARK),
    P(0, 3.16, 0, 0.42, 0.48, 0.42, LAMP_GLOW, { glow: 0.85 }),
    P(0, 3.46, 0, 0.50, 0.16, 0.50, BLACK),        // cap
    P(0, 3.58, 0, 0.14, 0.14, 0.14, BLACK),
    P(0, 3.55, 0, 0.18, 0.05, 0.18, SNOW),
  ],

  bench: [
    P(0, 0.42, 0, 1.70, 0.08, 0.48, WOOD),
    P(0, 0.66, -0.22, 1.70, 0.42, 0.08, WOOD_DARK),
    P(0, 0.50, 0, 1.72, 0.05, 0.50, SNOW),
    P(0.74, 0.21, 0, 0.10, 0.42, 0.46, BLACK),     // cast-iron ends
    P(-0.74, 0.21, 0, 0.10, 0.42, 0.46, BLACK),
    P(0.74, 0.72, -0.22, 0.10, 0.30, 0.10, BLACK),
    P(-0.74, 0.72, -0.22, 0.10, 0.30, 0.10, BLACK),
  ],

  // A bare winter tree: trunk, a fork, and four bare limbs. No canopy at all,
  // which is exactly the silhouette that says February in a park.
  'bare-tree': [
    P(0, 1.05, 0, 0.34, 2.10, 0.34, WOOD_DARK),
    P(0, 0.14, 0, 0.62, 0.28, 0.62, WOOD_DARK),
    P(0.42, 2.20, 0, 0.80, 0.12, 0.12, WOOD_DARK, { tiltZ: -0.5 }),
    P(-0.42, 2.35, 0.10, 0.80, 0.12, 0.12, WOOD_DARK, { tiltZ: 0.55 }),
    P(0, 2.50, 0.42, 0.12, 0.12, 0.80, WOOD_DARK, { tiltX: 0.5 }),
    P(0.30, 2.75, -0.30, 0.55, 0.10, 0.10, WOOD_DARK, { tiltZ: -0.7 }),
    P(0, 2.90, 0, 0.16, 0.55, 0.16, WOOD_DARK),
    P(0, 3.14, 0, 0.20, 0.07, 0.20, SNOW),
  ],

  'hot-dog-cart': [
    P(0, 0.62, 0, 1.20, 0.55, 0.72, METAL),
    P(0, 0.34, 0, 1.10, 0.10, 0.66, METAL_DARK),
    P(0.52, 0.20, 0.34, 0.08, 0.40, 0.40, BLACK),   // wheels
    P(-0.52, 0.20, 0.34, 0.08, 0.40, 0.40, BLACK),
    P(0, 0.92, 0, 1.10, 0.10, 0.62, METAL_DARK),
    P(0, 1.02, -0.10, 0.36, 0.14, 0.30, CANVAS),    // steam
    P(0, 1.62, 0, 1.30, 0.16, 0.80, CLOTH_RED),     // striped umbrella
    P(0, 1.62, 0.28, 1.30, 0.17, 0.24, CANVAS),
    P(0, 1.28, 0, 0.08, 0.62, 0.08, METAL_DARK),
    P(0, 1.74, 0, 0.10, 0.10, 0.10, LAMP_GLOW, { glow: 0.5 }),
  ],

  'skate-rack': [
    P(0, 0.06, 0, 1.30, 0.12, 0.54, WOOD_DARK),
    P(-0.58, 0.55, 0, 0.10, 0.98, 0.10, WOOD),
    P(0.58, 0.55, 0, 0.10, 0.98, 0.10, WOOD),
    P(0, 1.00, 0, 1.26, 0.08, 0.08, WOOD),
    P(-0.30, 0.78, 0.06, 0.20, 0.34, 0.14, CANVAS),   // hanging skates
    P(-0.30, 0.60, 0.10, 0.06, 0.06, 0.34, METAL),    // blade
    P(0.22, 0.80, 0.06, 0.20, 0.34, 0.14, 0x2b3a52),
    P(0.22, 0.62, 0.10, 0.06, 0.06, 0.34, METAL),
  ],

  bin: [
    P(0, 0.44, 0, 0.58, 0.88, 0.58, 0x3c4a3e),
    P(0, 0.20, 0, 0.62, 0.06, 0.62, METAL_DARK),
    P(0, 0.66, 0, 0.62, 0.06, 0.62, METAL_DARK),
    P(0, 0.92, 0, 0.64, 0.10, 0.64, BLACK),
    P(0, 1.00, 0, 0.30, 0.08, 0.30, SNOW),
    P(0.14, 1.02, 0.10, 0.16, 0.12, 0.10, CANVAS),    // overflowing paper
  ],

  'pretzel-stand': [
    P(0, 0.50, 0, 1.40, 0.10, 0.80, WOOD),
    P(-0.62, 0.25, 0.32, 0.10, 0.50, 0.10, WOOD_DARK),
    P(0.62, 0.25, 0.32, 0.10, 0.50, 0.10, WOOD_DARK),
    P(-0.62, 0.25, -0.32, 0.10, 0.50, 0.10, WOOD_DARK),
    P(0.62, 0.25, -0.32, 0.10, 0.50, 0.10, WOOD_DARK),
    P(0, 1.55, 0, 1.60, 0.18, 0.95, CLOTH_BLUE),      // awning
    P(0, 1.55, 0.30, 1.60, 0.19, 0.30, CANVAS),
    P(-0.66, 1.05, 0, 0.08, 1.00, 0.08, METAL_DARK),
    P(0.66, 1.05, 0, 0.08, 1.00, 0.08, METAL_DARK),
    P(0, 0.72, -0.10, 0.30, 0.34, 0.10, WOOD_PALE),   // pretzel on a hook
    P(0, 0.90, -0.10, 0.06, 0.24, 0.06, METAL),
    P(0.44, 0.62, 0.10, 0.34, 0.16, 0.30, 0xd9a45c),  // tray
  ],

  // -- Arctic ----------------------------------------------------------------

  // A cut ice-fishing hole: dark water in a rim of sawn ice, with the spoil
  // heaped beside it and a rod laid across.
  'ice-hole': [
    P(0, 0.05, 0, 1.10, 0.10, 1.10, ICE),
    P(0, 0.11, 0, 0.66, 0.02, 0.66, 0x16324a),
    P(0.62, 0.10, 0.20, 0.34, 0.20, 0.30, SNOW),
    P(-0.50, 0.08, -0.34, 0.28, 0.16, 0.24, ICE),
    P(0, 0.18, 0.30, 1.00, 0.05, 0.05, WOOD_DARK, { tiltY: 0.4 }),   // rod
    P(-0.44, 0.24, 0.18, 0.10, 0.14, 0.10, METAL_DARK),              // reel
  ],

  'fish-crate': [
    P(0, 0.20, 0, 0.85, 0.40, 0.60, WOOD_PALE),
    P(0, 0.06, 0, 0.90, 0.12, 0.64, WOOD_DARK),
    P(0, 0.42, 0, 0.80, 0.06, 0.56, ICE),
    P(0.14, 0.47, 0.06, 0.44, 0.12, 0.16, 0x7f95a8, { tiltY: 0.3 }),  // fish
    P(-0.18, 0.46, -0.08, 0.40, 0.11, 0.15, 0x93a8b8, { tiltY: -0.5 }),
    P(0.30, 0.48, -0.12, 0.14, 0.10, 0.10, FLESH),
  ],

  // A field radio mast: guyed lattice with a dish and a warning light.
  'radio-mast': [
    P(0, 0.10, 0, 0.80, 0.20, 0.80, METAL_DARK),
    P(0, 1.60, 0, 0.20, 3.00, 0.20, METAL),
    P(0, 0.90, 0, 0.46, 0.08, 0.46, METAL_DARK),   // lattice collars
    P(0, 1.80, 0, 0.42, 0.08, 0.42, METAL_DARK),
    P(0, 2.60, 0, 0.34, 0.08, 0.34, METAL_DARK),
    P(0.34, 2.30, 0, 0.44, 0.44, 0.10, CANVAS),    // dish
    P(0.18, 2.30, 0, 0.24, 0.05, 0.05, METAL_DARK),
    P(0, 3.20, 0, 0.16, 0.16, 0.16, CLOTH_RED, { glow: 0.9 }),
    P(0.50, 0.70, 0.50, 0.05, 1.50, 0.05, METAL_DARK, { tiltZ: 0.35, tiltX: 0.35 }),
    P(-0.50, 0.70, -0.50, 0.05, 1.50, 0.05, METAL_DARK, { tiltZ: -0.35, tiltX: -0.35 }),
  ],
});

export const PROP_IDS = Object.freeze(Object.keys(PROPS));

// How much a scattered prop's size is allowed to wander, and how far it may be
// nudged off tile centre. Props all sitting dead centre on a 1 m grid is the
// same wallpaper problem the ground-wear pass hit with boot prints.
export const SCATTER_JITTER = Object.freeze({
  scale: [0.86, 1.18],
  offset: 0.28,
});

// Props that must NOT be rotated to a random yaw, because they have a right
// way up relative to the world rather than just to themselves.
export const FIXED_YAW = Object.freeze(new Set(['weather-vane']));
